//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiOnBoarding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBDTPlanRecurso
    {
        public int IdPlanRecurso { get; set; }
        public int IdPlan { get; set; }
        public int IdRecurso { get; set; }
        public bool Activo { get; set; }
        public string UsuarioInserto { get; set; }
        public System.DateTime FechaInserto { get; set; }
        public string UsuarioModifico { get; set; }
        public Nullable<System.DateTime> FechaModifico { get; set; }
    
        public virtual OBDTPlan OBDTPlan { get; set; }
        public virtual OBDTRecurso OBDTRecurso { get; set; }
    }
}
