//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiOnBoarding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBDTPlan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OBDTPlan()
        {
            this.OBDTPlanPeriodoEvaluacion = new HashSet<OBDTPlanPeriodoEvaluacion>();
            this.OBDTPlanRecurso = new HashSet<OBDTPlanRecurso>();
        }
    
        public int IdPlan { get; set; }
        public int CodigoPlan { get; set; }
        public string NombrePlan { get; set; }
        public int IdPuesto { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
        public bool Activo { get; set; }
        public string UsuarioInserto { get; set; }
        public System.DateTime FechaInserto { get; set; }
        public string UsuarioModifico { get; set; }
        public Nullable<System.DateTime> FechaModifico { get; set; }
    
        public virtual OBDTEmpleado OBDTEmpleado { get; set; }
        public virtual OBDTPuesto OBDTPuesto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OBDTPlanPeriodoEvaluacion> OBDTPlanPeriodoEvaluacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OBDTPlanRecurso> OBDTPlanRecurso { get; set; }
    }
}
