//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiOnBoarding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBDTAspectoConductualItemEvaluacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OBDTAspectoConductualItemEvaluacion()
        {
            this.OBDTEvaluacionAspectoConductual = new HashSet<OBDTEvaluacionAspectoConductual>();
        }
    
        public int IdAspectoConductualItemEvaluacion { get; set; }
        public int IdAspectoConductual { get; set; }
        public int IdItemEvaluacion { get; set; }
        public int IdPorcentaje { get; set; }
        public bool Activo { get; set; }
        public string UsuarioInserto { get; set; }
        public System.DateTime FechaInserto { get; set; }
        public string UsuarioModifico { get; set; }
        public Nullable<System.DateTime> FechaModifico { get; set; }
    
        public virtual OBDTAspectoConductual OBDTAspectoConductual { get; set; }
        public virtual OBDTItemEvaluacion OBDTItemEvaluacion { get; set; }
        public virtual OBDTPorcentaje OBDTPorcentaje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OBDTEvaluacionAspectoConductual> OBDTEvaluacionAspectoConductual { get; set; }
    }
}
