//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiOnBoarding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBDTEmpleadoPuesto
    {
        public int IdEmpleadoPuesto { get; set; }
        public int IdEmpleado { get; set; }
        public int IdPuesto { get; set; }
        public bool Activo { get; set; }
        public string UsuarioInserto { get; set; }
        public System.DateTime FechaInserto { get; set; }
        public string UsuarioModifico { get; set; }
        public Nullable<System.DateTime> FechaModifico { get; set; }
    
        public virtual OBDTEmpleado OBDTEmpleado { get; set; }
        public virtual OBDTPuesto OBDTPuesto { get; set; }
    }
}
