//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnBoarding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBDTAspectoConductual
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OBDTAspectoConductual()
        {
            this.OBDTAspectoConductualItemEvaluacion = new HashSet<OBDTAspectoConductualItemEvaluacion>();
        }
    
        public int IdAspectoConductual { get; set; }
        public int CodigoAspectoConductual { get; set; }
        public string NombreAspectoConductual { get; set; }
        public int IdObjetivoAprendizaje { get; set; }
        public bool Activo { get; set; }
        public string UsuarioInserto { get; set; }
        public System.DateTime FechaInserto { get; set; }
        public string UsuarioModifico { get; set; }
        public Nullable<System.DateTime> FechaModifico { get; set; }
    
        public virtual OBDTObjetivoAprendizaje OBDTObjetivoAprendizaje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OBDTAspectoConductualItemEvaluacion> OBDTAspectoConductualItemEvaluacion { get; set; }
    }
}
