//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnBoarding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBDTPeriodoEvaluacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OBDTPeriodoEvaluacion()
        {
            this.OBDTEvaluacionAspectoConductual = new HashSet<OBDTEvaluacionAspectoConductual>();
            this.OBDTEvaluacionAspectoTecnico = new HashSet<OBDTEvaluacionAspectoTecnico>();
            this.OBDTPlanPeriodoEvaluacion = new HashSet<OBDTPlanPeriodoEvaluacion>();
        }
    
        public int IdPeriodoEvaluacion { get; set; }
        public int CodigoPeriodoEvaluacion { get; set; }
        public string NombrePeriodoEvaluacion { get; set; }
        public System.DateTime FechaPeriodoEvaluacion { get; set; }
        public bool Activo { get; set; }
        public string UsuarioInserto { get; set; }
        public System.DateTime FechaInserto { get; set; }
        public string UsuarioModifico { get; set; }
        public Nullable<System.DateTime> FechaModifico { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OBDTEvaluacionAspectoConductual> OBDTEvaluacionAspectoConductual { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OBDTEvaluacionAspectoTecnico> OBDTEvaluacionAspectoTecnico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OBDTPlanPeriodoEvaluacion> OBDTPlanPeriodoEvaluacion { get; set; }
    }
}
