//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnBoarding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBDTAspectoTecnicoItemEvaluacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OBDTAspectoTecnicoItemEvaluacion()
        {
            this.OBDTEvaluacionAspectoTecnico = new HashSet<OBDTEvaluacionAspectoTecnico>();
        }
    
        public int IdAspectoTecnicoItemEvaluacion { get; set; }
        public int IdAspectoTecnico { get; set; }
        public int IdItemEvaluacion { get; set; }
        public int IdPorcentaje { get; set; }
        public bool Activo { get; set; }
        public string UsuarioInserto { get; set; }
        public System.DateTime FechaInserto { get; set; }
        public string UsuarioModifico { get; set; }
        public Nullable<System.DateTime> FechaModifico { get; set; }
    
        public virtual OBDTAspectoTecnico OBDTAspectoTecnico { get; set; }
        public virtual OBDTItemEvaluacion OBDTItemEvaluacion { get; set; }
        public virtual OBDTPorcentaje OBDTPorcentaje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OBDTEvaluacionAspectoTecnico> OBDTEvaluacionAspectoTecnico { get; set; }
    }
}
