//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnBoarding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBDTEvaluacionAspectoConductual
    {
        public int IdEvaluacionAspectoConductual { get; set; }
        public int IdAspectoConductualItemEvaluacion { get; set; }
        public int IdPeriodoEvaluacion { get; set; }
        public decimal Valor { get; set; }
        public bool Activo { get; set; }
        public string UsuarioInserto { get; set; }
        public System.DateTime FechaInserto { get; set; }
        public string UsuarioModifico { get; set; }
        public Nullable<System.DateTime> FechaModifico { get; set; }
    
        public virtual OBDTAspectoConductualItemEvaluacion OBDTAspectoConductualItemEvaluacion { get; set; }
        public virtual OBDTPeriodoEvaluacion OBDTPeriodoEvaluacion { get; set; }
    }
}
