//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnBoarding.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BIOSALCTEMPEntities : DbContext
    {
        public BIOSALCTEMPEntities()
            : base("name=BIOSALCTEMPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<OBDTAspectoConductual> OBDTAspectoConductual { get; set; }
        public virtual DbSet<OBDTAspectoConductualItemEvaluacion> OBDTAspectoConductualItemEvaluacion { get; set; }
        public virtual DbSet<OBDTAspectoTecnico> OBDTAspectoTecnico { get; set; }
        public virtual DbSet<OBDTAspectoTecnicoItemEvaluacion> OBDTAspectoTecnicoItemEvaluacion { get; set; }
        public virtual DbSet<OBDTEmpleado> OBDTEmpleado { get; set; }
        public virtual DbSet<OBDTEmpleadoPuesto> OBDTEmpleadoPuesto { get; set; }
        public virtual DbSet<OBDTEvaluacionAspectoConductual> OBDTEvaluacionAspectoConductual { get; set; }
        public virtual DbSet<OBDTEvaluacionAspectoTecnico> OBDTEvaluacionAspectoTecnico { get; set; }
        public virtual DbSet<OBDTItemEvaluacion> OBDTItemEvaluacion { get; set; }
        public virtual DbSet<OBDTObjetivoAprendizaje> OBDTObjetivoAprendizaje { get; set; }
        public virtual DbSet<OBDTPeriodoEvaluacion> OBDTPeriodoEvaluacion { get; set; }
        public virtual DbSet<OBDTPlan> OBDTPlan { get; set; }
        public virtual DbSet<OBDTPlanPeriodoEvaluacion> OBDTPlanPeriodoEvaluacion { get; set; }
        public virtual DbSet<OBDTPlanRecurso> OBDTPlanRecurso { get; set; }
        public virtual DbSet<OBDTPorcentaje> OBDTPorcentaje { get; set; }
        public virtual DbSet<OBDTPuesto> OBDTPuesto { get; set; }
        public virtual DbSet<OBDTRecurso> OBDTRecurso { get; set; }
    }
}
